/**
 * esbuild virtual modules — modules with no file on disk, produced by a plugin
 * in `esbuild.config.mjs` at build time. TypeScript cannot resolve them, so
 * their shape is declared here to match what the plugin emits.
 */

/**
 * The reader's build output, gzipped and base64-encoded one file at a time.
 * Generated by `inlineResourcePlugin` over `reader/reader/build/obsidian`.
 */
declare module "virtual:reader-resources" {
    /** Every resource path, in the `./pdf/web/viewer.html` form. */
    export function resourceKeys(): string[];

    /**
     * The gzipped, base64-encoded contents of one resource, or `undefined` for
     * a key the build did not emit.
     */
    export default function resourceContext(key: string): string | undefined;
}
